baseurl = "https://www.bibledocs.org/"
title = "BibleDocs"
theme = "spartan"
author = "Steven Tammen"
canonifyurls = true
paginate = 10

# Ignore assessment files, Anki flashcard files, and checklist files
ignoreFiles = ["assessment\\.md$", "anki-flashcards\\.md$", "checklist\\.xlsx$"]

[indexes]
  category = "categories"
  tag = "tags"

[params]
  # Shown in the home page
  subtitle = "Scripture-centered writings for the Christian life"
  googleAnalytics = ""
  disqus = ""
  # CSS name for highlight.js
  highlightjs = "solarized-dark"
  # additional languages for highlight.js (for all pages)
  highlightjs_extra_languages = ["lisp", "r", "autohotkey"]
  dateFormat = "02 Jan 2006"

[blackfriday]
  fractions = false
  # Blocking (c) -> copyright symbol, etc.
  # https://github.com/kaushalmodi/ox-hugo/issues/104
  # https://gohugo.io/getting-started/configuration-markup
  smartypants = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  
[menu]

  # Shown in the side menu.
  [[menu.navigation]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.navigation]]
    name = "Contact"
    pre = "<i class='fas fa-phone fa-fw'></i>"
    weight = 2
	  identifier = "contact"
    url = "/contact/"
  [[menu.navigation]]
    name = "About the Author"
    pre = "<i class='fas fa-user fa-fw'></i>"
    weight = 3
	  identifier = "about-the-author"
    url = "/about-the-author/"
  [[menu.navigation]]  
    name = "About the Site"
    pre = "<i class='fas fa-sitemap fa-fw'></i>"
    weight = 4
    identifier = "about-the-site"
    url = "/about-the-site/"
  [[menu.navigation]]  
    name = "Progress Summaries"
    pre = "<i class='fa fa-calendar fa-fw'></i>"
    weight = 5
    identifier = "ministry-progress-summaries"
    url = "/ministry-progress-summaries/"
	
	
#  [[menu.content]]
#    name = "Topical Studies"
#    pre = "<i class='fas fa-file-alt fa-fw'></i>"
#    weight = 2
#    identifier = "topical-studies"
#    url = "/topical-studies/"
  [[menu.content]]
    name = "CrossTalk Bible Study"
    pre = "<i class='fas fa-file-alt fa-fw'></i>"
    weight = 1
    identifier = "crosstalk-bible-study"
    url = "/crosstalk-bible-study/"
  [[menu.content]]
    name = "Icthys Bible Study"
    pre = "<i class='fas fa-file-alt fa-fw'></i>"
    weight = 2
    identifier = "ichthys-bible-study"
    url = "/ichthys-bible-study/"
#  [[menu.content]]
#    name = "Pages"
#    pre = "<i class='fas fa-file-alt fa-fw'></i>"
#    weight = 3
#    identifier = "pages"
#    url = "/pages/"
  [[menu.content]]
    name = "Shorter Topical"
    pre = "<i class='fab fa-youtube fa-fw'></i>"
    weight = 3
    identifier = "shorter-topical-studies"
    url = "/shorter-topical-studies/"
  [[menu.content]]
    name = "Longer Topical"
    pre = "<i class='fab fa-youtube fa-fw'></i>"
    weight = 4
    identifier = "longer-topical-studies"
    url = "/longer-topical-studies/"
  [[menu.content]]
    name = "Verse-by-verse"
    pre = "<i class='fab fa-youtube fa-fw'></i>"
    weight = 5
    identifier = "verse-by-verse-studies"
    url = "/verse-by-verse-studies/"
  [[menu.content]]
    name = "Q&As"
    pre = "<i class='fab fa-youtube fa-fw'></i>"
    weight = 6
    identifier = "questions-and-answers"
    url = "/questions-and-answers/"
#  [[menu.content]]
#    name = "Ministry Info"
#    pre = "<i class='fas fa-file-alt fa-fw'></i>"
#    weight = 7
#    identifier = "ministry-info"
#    url = "/ministry-info/"
#  [[menu.content]]
#    name = "Guides"
#    pre = "<i class='fab fa-youtube fa-fw'></i>"
#    weight = 8
#    identifier = "guides"
#    url = "/guides/"
#  [[menu.content]]
#    name = "Video Series"
#    pre = "<i class='fab fa-youtube fa-fw'></i>"
#    weight = 9
#    identifier = "video-series"
#    url = "/video-series/"
#  [[menu.content]]
#    name = "Greek Resources"
#    pre = "<i class='fas fa-file-alt fa-fw'></i>"
#    weight = 10
#    identifier = "greek-resources"
#    url = "/greek-resources/"
#  [[menu.content]]
#    name = "Hebrew Resources"
#    pre = "<i class='fas fa-file-alt fa-fw'></i>"
#    weight = 11
#    identifier = "hebrew-resources"
#    url = "/hebrew-resources/"	


  [[menu.community]]
    name = "Overview"
    pre = "<i class='fas fa-sitemap fa-fw'></i>"
    weight = 1
    identifier = "community-overview"
    url = "/community-overview"
  [[menu.community]]
    name = "Meetings"
    pre = "<i class='fas fa-users fa-fw'></i>"
    weight = 2
    identifier = "community-meetings"
    url = "/community-meetings"
#  [[menu.community]]
#    name = "Forums"
#    pre = "<i class='fab fa-discourse fa-fw'></i>"
#    weight = 3
#    identifier = "forums"
#    url = "https://community.bibledocs.org/"
#  [[menu.community]]
#    name = "Prayer List"
#    pre = "<i class='fas fa-praying-hands fa-fw'></i>"
#    weight = 4
#    identifier = "prayer-list"
#    url = "/prayer-list/"
#  [[menu.community]]
#    name = "Contact Network"
#    pre = "<i class='fas fa-address-book fa-fw'></i>"
#    weight = 5
#    identifier = "contact-network"
#    url = "/site/contact-network/"
	
	
#  [[menu.meta]]
#    name = "Links"
#    pre = "<i class='fas fa-link fa-fw'></i>"
#    weight = 3
#    identifier = "links"
#    url = "/site/links/"
  [[menu.meta]]
    name = "Settings"
    pre = "<i class='fas fa-cog fa-fw'></i>"
    weight = 4
    identifier = "settings"
    url = "/settings/"
#  [[menu.meta]]  
#    name = "Glossary"
#    pre = "<i class='fas fa-list fa-fw'></i>"
#    weight = 5
#    identifier = "glossary"
#    url = "/site/glossary/"
  [[menu.meta]]
    name = "Subject Index"
    pre = "<i class='fas fa-list fa-fw'></i>"
    weight = 6
    identifier = "subject-index"
    url = "/subject-index/"
#  [[menu.meta]]
#    name = "Passage Index"
#    pre = "<i class='fas fa-list fa-fw'></i>"
#    weight = 7
#    identifier = "passage-index"
#    url = "/site/passage-index/"
#  [[menu.meta]]
#    name = "Translation Index"
#    pre = "<i class='fas fa-list fa-fw'></i>"
#    weight = 8
#    identifier = "translation-index"
#    url = "/site/translation-index/"
  [[menu.meta]]
    name = "Resource Index"
    pre = "<i class='fas fa-list fa-fw'></i>"
    weight = 9
    identifier = "resource-index"
    url = "/resource-index/"
  [[menu.meta]]  
    name = "Mailing List"
    pre = "<i class='fas fa-envelope fa-fw'></i>"
    weight = 29
    identifier = "mailing-list"
    url = "/mailing-list/"
#  [[menu.meta]]  
#    name = "RSS"
#    pre = "<i class='fas fa-rss fa-fw'></i>"
#    weight = 30
#    identifier = "rss"
#    url = "/rss/"
	
	